### ISSUE TITLE
NX-OSv 9000 Large Memory Flavor Needed for BGP

### ISSUE THREAD

**Issue by gve-vse-tim** [DevNetSandbox/sbx_multi_ios#13]
The default VIRL simulation provides 6GB and 1 vCPU for the NX-OSv 9000 image using the NX-OSv 9000 flavor within VIRL. 

In the previous version of the sandbox, there were two flavors: 1 vCPU/4GB and a 2vCPU/8GB.

The NX-OSv image needs 8GB in order to do BGP.

**Comment by kecorbin** [comment]
I believe this has been completed by the sandbox team.

**Comment by kecorbin** [comment]
@gve-vse-tim  can you confirm this is fixed?  if so, we can close this issue

**Comment by gve-vse-tim** [comment]
Confirmed - they changed the default flavor for NX-OSV 9000 to be 8GB instead of the 6GB value.  All good now.
