### ISSUE TITLE
Disable SSH known hosts 

### ISSUE THREAD

**Issue by kecorbin** [DevNetSandbox/sbx_multi_ios#18]
known_hosts are currently stored, such that if a simulation is stopped/started multiple times the host key will change and user gets an error.  We should add the following to ~/.ssh/config

```
Host 172.16.30.*
   StrictHostKeyChecking no
   UserKnownHostsFile=/dev/null
```
@hpreston thoughts?

**Comment by hpreston** [comment]
@kecorbin agreed... this should be a simple and safe add to the DevBox sync_script to just echo that into the config file... 

Might as well add these others too as it'll help with other sandboxes for the same/similar reason.. 

```
Host 172.20.*.*
  StrictHostKeyChecking no
  UserKnownHostsFile=/dev/null
Host 10.10.20.*
   StrictHostKeyChecking no
   UserKnownHostsFile=/dev/null
Host 172.16.30.*
   StrictHostKeyChecking no
   UserKnownHostsFile=/dev/null
```

As you opened the issue, can you do the PR :-)

**Comment by kecorbin** [comment]
i guess this was opened on the wrong repo closing here. FYI - https://github.com/DevNetSandbox/sbx_devbox/pull/6
